### ISSUE TITLE
编译报错 Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin

### ISSUE THREAD

**Issue by jeftom** [jmdhappy/xxpay-master#2]
错误信息：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project xxpay-service: There are test failures.

环境：
Apache Maven 3.3.9
Java version: 1.8.0_112
OS name: "mac os x", version: "10.11.6"

不知道是不是我操作的不对？

**Comment by jmdhappy** [comment]
编译时，关闭test
